apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: infra-postgres-set-test
  namespace: co-postgres-settest
  labels:
    team: infra
spec:
  teamId: infra
  volume:
    storageClass: ebs-sc
    size: "1Gi"
  numberOfInstances: 3
  users:
    postgres:           # database owner
    - superuser
    - createdb
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  databases:
    defaultdb: postgres
  postgresql:
    version: "11"