apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: '${parameters.team_id}-${parameters.pod_name_suffix}'
  namespace: '${parameters.namespace}'
  labels:
    team: '${parameters.team_id}'
spec:
  teamId: '${parameters.team_id}'
  volume:
    storageClass: ebs-sc
    size: '${parameters.volume_size}Gi'
  numberOfInstances: '${#toInt(parameters.instances)}'
  users:
    postgres:           # database owner
    - superuser
    - createdb
    appuser: []
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  databases:
    '${parameters.defaultdb}': postgres
  postgresql:
    version: "${parameters.postgres_version}"
