apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- orchestration/postgresd-deployment.yaml
- orchestration/postgresd-service.yaml
- orchestration/hydra-migrate-pod.yaml
- orchestration/hydra-deployment.yaml
- orchestration/hydra-service.yaml
- orchestration/hydra-virtual-services.yaml
- orchestration/istio-gateway-config.yaml

namespace: default
