apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgresd-deployment.yaml
- postgresd-service.yaml
- hydra-migrate-pod.yaml
- hydra-deployment.yaml
- hydra-service.yaml
# - hydra-virtual-services.yaml
# - istio-gateway-config.yaml

namespace: default

# Take 3
